name: Instant Merge Konflux PRs

on:
  pull_request:
    types:
      - opened
    paths:
      - config/base/*.env

permissions:
  contents: write
  pull-requests: write
  checks: write
  security-events: write
  statuses: write

jobs:
  instant-merge:
    runs-on: ubuntu-latest
    steps:
      - name: instant-merge
        if: ${{ github.event.sender.login == 'red-hat-konflux[bot]' && ( contains(github.event.pull_request.title, 'Update caikit-nlp-') || contains(github.event.pull_request.title, 'Update vllm-cuda-') || contains(github.event.pull_request.title, 'Update vllm-rocm-') || contains(github.event.pull_request.title, 'Update vllm-gaudi-') ) }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          gh pr merge --merge --admin ${{ github.event.pull_request.html_url }}
